import { LinearGradient } from 'expo-linear-gradient';
import type { ImageSourcePropType } from 'react-native';
import { Image, Modal, Pressable, ScrollView, StyleSheet, Text, View, useWindowDimensions } from 'react-native';

import { SafeIonicons } from '@/components/icons/SafeIonicons';
import { runit, runitFont, runitTextGlowCyan, runitTextGlowPink } from '@/lib/runitArcadeTheme';

/** Generated by `npm run capture:how-it-works` from the exported web build. */
const STEP_IMAGES: ImageSourcePropType[] = [
  require('../../assets/how-it-works/01-home.png'),
  require('../../assets/how-it-works/02-minigames.png'),
  require('../../assets/how-it-works/03-queue.png'),
  require('../../assets/how-it-works/04-tap-dash.png'),
];

const STEPS: { title: string; body: string }[] = [
  {
    title: 'Choose your game',
    body: 'Each head-to-head queue is a live skill contest on a minigame — the same titles you play in Arcade, but here you’re matched against another player.',
  },
  {
    title: 'Pick a contest tier',
    body: 'Your entry pays for match access to that tier. The prize shown is for the top performer in that contest. Wallet funds cover entries where needed.',
  },
  {
    title: 'We match you',
    body: 'We pair you with someone searching the same game and tier. Quick Match jumps the line when pools are busy.',
  },
  {
    title: 'Play & compare scores',
    body: 'You both play the same run. Highest score wins the tier prize; everyone still earns Arcade Credits to keep playing.',
  },
];

type Props = {
  visible: boolean;
  onClose: () => void;
};

function StepScreenshot({ source }: { source: ImageSourcePropType }) {
  return (
    <View style={styles.shotOuter}>
      <LinearGradient
        colors={['rgba(236,72,153,0.45)', 'rgba(34,211,238,0.2)']}
        start={{ x: 0, y: 0 }}
        end={{ x: 1, y: 1 }}
        style={styles.shotFrame}
      >
        <Image
          source={source}
          style={styles.shotImg}
          resizeMode="cover"
          accessibilityRole="image"
          accessibilityIgnoresInvertColors
        />
      </LinearGradient>
    </View>
  );
}

export function HowItWorksModal({ visible, onClose }: Props) {
  const { width } = useWindowDimensions();
  const maxSheet = Math.min(440, width - 28);

  return (
    <Modal animationType="fade" transparent visible={visible} onRequestClose={onClose}>
      <Pressable style={styles.backdrop} onPress={onClose}>
        <Pressable style={[styles.sheet, { maxWidth: maxSheet }]} onPress={(e) => e.stopPropagation()}>
          <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}>
            <View style={styles.heroRow}>
              <Image
                source={require('../../assets/images/run-it-arcade-logo.png')}
                style={styles.logoImg}
                resizeMode="contain"
                accessibilityIgnoresInvertColors
              />
              <View style={{ flex: 1 }}>
                <Text style={[styles.title, { fontFamily: runitFont.black }, runitTextGlowPink]}>How it works</Text>
                <Text style={[styles.subtitle, runitTextGlowCyan]}>Head-to-head arcade in four steps</Text>
              </View>
            </View>

            {STEPS.map((step, i) => (
              <View key={step.title} style={styles.stepBlock}>
                <View style={styles.stepBadge}>
                  <Text style={styles.stepBadgeTxt}>{i + 1}</Text>
                </View>
                <StepScreenshot source={STEP_IMAGES[i]!} />
                <Text style={styles.stepTitle}>{step.title}</Text>
                <Text style={styles.stepBody}>{step.body}</Text>
              </View>
            ))}

            <Pressable onPress={onClose} style={({ pressed }) => [styles.cta, pressed && { opacity: 0.9 }]}>
              <LinearGradient
                colors={[runit.neonPink, '#c9184a']}
                start={{ x: 0, y: 0 }}
                end={{ x: 1, y: 1 }}
                style={styles.ctaGrad}
              >
                <Text style={[styles.ctaTxt, { fontFamily: runitFont.bold }]}>Got it</Text>
                <SafeIonicons name="arrow-forward" size={20} color="#fff" />
              </LinearGradient>
            </Pressable>
          </ScrollView>
        </Pressable>
      </Pressable>
    </Modal>
  );
}

const styles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(2,6,15,0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 24,
  },
  sheet: {
    width: '100%',
    maxHeight: '92%',
    borderRadius: 20,
    backgroundColor: 'rgba(10,12,24,0.97)',
    borderWidth: 1,
    borderColor: 'rgba(236,72,153,0.35)',
    overflow: 'hidden',
  },
  scroll: {
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 22,
  },
  heroRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 18,
  },
  logoImg: {
    width: 56,
    height: 56,
  },
  title: {
    fontSize: 22,
    letterSpacing: 0.5,
    color: '#fff',
  },
  subtitle: {
    marginTop: 4,
    fontSize: 13,
    fontWeight: '700',
  },
  stepBlock: {
    marginBottom: 22,
  },
  stepBadge: {
    alignSelf: 'flex-start',
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(0,240,255,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(0,240,255,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  stepBadgeTxt: {
    color: runit.neonCyan,
    fontSize: 13,
    fontWeight: '900',
  },
  shotOuter: {
    alignSelf: 'center',
    width: '100%',
    maxWidth: 340,
    marginBottom: 10,
  },
  shotFrame: {
    borderRadius: 16,
    padding: 2,
  },
  shotImg: {
    width: '100%',
    aspectRatio: 390 / 780,
    borderRadius: 14,
    backgroundColor: 'rgba(15,23,42,0.9)',
  },
  stepTitle: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '900',
    marginBottom: 6,
    marginTop: 4,
  },
  stepBody: {
    color: 'rgba(203,213,225,0.92)',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '500',
  },
  cta: {
    marginTop: 4,
    borderRadius: 14,
    overflow: 'hidden',
  },
  ctaGrad: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
  },
  ctaTxt: {
    color: '#fff',
    fontSize: 16,
    letterSpacing: 0.5,
  },
});
