export const queryKeys = {
  homeLobby: () => ['homeLobby'] as const,
  homeH2hBoard: () => ['homeH2hBoard'] as const,
  profile: (userId: string) => ['profile', userId] as const,
  profileByUsername: (username: string) => ['profileUsername', username] as const,
  tournaments: (filters?: Record<string, string>) => ['tournaments', filters ?? {}] as const,
  tournament: (id: string) => ['tournament', id] as const,
  tournamentRules: (id: string) => ['tournamentRules', id] as const,
  tournamentBracket: (id: string) => ['tournamentBracket', id] as const,
  weeklyRace: (dayKey: string) => ['weeklyRace', dayKey] as const,
  userAchievements: (userId: string) => ['userAchievements', userId] as const,
  leaderboard: (scope: string, seasonId: string | null, region: string) =>
    ['leaderboard', scope, seasonId, region] as const,
  transactions: (userId: string) => ['transactions', userId] as const,
  withdrawPlatformFeeBps: () => ['withdrawPlatformFeeBps'] as const,
  seasonActive: () => ['seasonActive'] as const,
  ratings: (userId: string) => ['ratings', userId] as const,
  userStats: (userId: string) => ['userStats', userId] as const,
  recentMatches: (userId: string) => ['recentMatches', userId] as const,
  prizeCatalog: () => ['prizeCatalog'] as const,
  matchSession: (matchSessionId: string) => ['matchSession', matchSessionId] as const,
  h2hTapDashScores: (matchSessionId: string) => ['h2hTapDashScores', matchSessionId] as const,
};
